### ISSUE TITLE
Path issues

### ISSUE THREAD

**Issue by biuboomc** [rllm-project/rllm#1]
Hi! 
We have found some problems in the example code when running the example code(GCN). From the code we assume we should run `python train.py` from directory `rllm/examples/gcn/cora`. However, this would lead to many import errors. After thorough investigation, we believe there are three major errors that exist in the code:
- The graph convolutional layer is imported from `pygcn` instead of `GCNconv.py` in this repo (`rllm/examples/gcn/cora/model.py`)
- typo: `dataset` -> `datasets` (such as `rllm/datasets/cora.py` and other codes in this dir)
- When using string concatenation for path finding, the first character should be `'/'`. (such as `current_path + '../../data'` to `current_path + '/../data'`)

 We have corrected these errors and run gcn on cora datasets successfully. How should we submit our code?
Thank you UwU.

**Comment by rllm-project** [comment]
The problems mentioned have been solved. It is welcomed if you fork this repo and open a pull request with your contributions.
